[needle]
# all data in mm
length = 200
radius = 2
ablation_center_dist = 15

[ablation]
# all data in mm and on one side
radius_z = 25
radius_r = 15
tumor_margin = 10

[images]
# ct standard settings
window_size = 400
window_center = 50

[scoring]
angle_threshold = 80

# minimum mm of healthy tissue needle needs to
# traverse before entering tumor tissue.
healthy_entrance_min_mm = 10

score_threshold = 0.5
min_patch_size = 10

# weights for the scoring function. manually changing this isn't recommended  
weights = 1,1,1,1,0.1

[output]