# this sets each organ's margin values
# first value = margin (in mm) 
# second value = resistance fraction
[margins]
liver = 0, 1
liver_vessels = 0, 1
liver_tumor = 0, 1

# cardiovascular
heart = 0, 1
aorta = 0, 1
pulmonary_vein = 0, 1
brachiocephalic_trunk = 0, 1
subclavian_artery = 0, 1
common_carotid_artery = 0, 1
brachiocephalic_vein = 0, 1
atrial_appendage_left = 0, 1
superior_vena_cava = 0, 1
inferior_vena_cava = 0, 1
portal_vein_and_splenic_vein = 0, 1
iliac_artery = 0, 1
iliac_vena = 0, 1

# respiratory / thoracic
lung = 0, 1
esophagus = 0, 1 
trachea = 0, 1

# abdominal
kidney = 0, 1
stomach = 0, 1
spleen = 0, 1 
gallbladder = 0, 1
pancreas = 0, 1
small_bowel = 0, 1
duodenum = 0, 1
colon = 0, 1
urinary_bladder = 0, 1
prostate = 0, 1

# glands
adrenal_gland = 0, 1
thyroid_gland = 0, 1

# skeletal
sacrum = 0, 1 
vertebrae = 0, 1
humerus = 0, 1
scapula = 0, 1
clavicula = 0, 1
femur = 0, 1
hip = 0, 1
rib = 1.5, 0.5
sternum = 0, 1
costal_cartilages = 0, 1
skull = 0, 1

# muscular
gluteus_maximus = 0, 1 
gluteus_medius = 0, 1
gluteus_minimus = 0, 1
autochthon = 0, 1
iliopsoas = 0, 1

# nervous system
brain = 0, 1
spinal_cord = 0, 1