# this sets each organ's opacity value
# higher opacity means trajectories should avoid it
# 1 means the organ is opaque: the needle can't go through it
[opacity]
liver_vessels = 1
liver = 0.0

# non-segmentation
body = 0.01

# cardiovascular
heart = 1
aorta = 1
pulmonary_vein = 1
brachiocephalic_trunk = 1
subclavian_artery = 1
common_carotid_artery = 1
brachiocephalic_vein = 1
atrial_appendage_left = 1
superior_vena_cava = 1
inferior_vena_cava = 1
portal_vein_and_splenic_vein = 1
iliac_artery = 1
iliac_vena = 1

# respiratory / thoracic
lung = 1
esophagus = 1 
trachea = 1

# abdominal
kidney = 1
stomach = 1
spleen = 0.1 
gallbladder = 0.1
pancreas = 0.1
small_bowel = 0.1
duodenum = 0.1
colon = 0.1
urinary_bladder = 0.1
prostate = 0.1

# glands
adrenal_gland = 0.1
thyroid_gland = 0.1

# skeletal
sacrum = 0.1 
vertebrae = 0.1
humerus = 0.1
scapula = 0.1
clavicula = 1
femur = 1
hip = 1
rib = 1
sternum = 0.1
costal_cartilages = 0.1
skull = 0.1

# muscular
gluteus_maximus = 0.1 
gluteus_medius = 0.1
gluteus_minimus = 0.1
autochthon = 0.1
iliopsoas = 0.1

# nervous system
brain = 1
spinal_cord = 1