# this sets each organ's margin values
# first value = margin (in mm) 
# second value = resistance fraction
[margins]
liver = 0, 0.9
liver_vessels = 3, 0.8
liver_tumor = 0, 0.9

# cardiovascular
heart = 10, 0.9
aorta = 10, 0.9
pulmonary_vein = 5, 0.8
brachiocephalic_trunk = 0, 0.9
subclavian_artery = 10, 0.9
common_carotid_artery = 10, 0.9
brachiocephalic_vein = 5, 0.9
atrial_appendage_left = 5, 0.9
superior_vena_cava = 10, 0.9
inferior_vena_cava = 10, 0.9
portal_vein_and_splenic_vein = 5, 0.9
iliac_artery = 5, 0.9
iliac_vena = 5, 0.9

# respiratory / thoracic
lung = 5, 0.5
esophagus = 5, 1
trachea = 5, 1

# abdominal
kidney = 5, 0.9
stomach = 5, 0.8
spleen = 5, 0.9 
gallbladder = 5, 0.9
pancreas = 5, 0.9
small_bowel = 5, 0.8
duodenum = 5, 0.1
colon = 5, 0.9
urinary_bladder = 5, 0.9
prostate = 5, 0.9

# glands
adrenal_gland = 0, 0.9
thyroid_gland = 0, 0.9

# skeletal
sacrum = 3, 0.5
vertebrae = 3, 0.5
humerus = 3, 0.5
scapula = 3, 0.5
clavicula = 3, 0.5
femur = 3, 0.5
hip = 3, 0.5
rib = 3, 0.5
sternum = 3, 0.5
costal_cartilages = 3, 0.5
skull = 3, 0.5

# muscular
gluteus_maximus = 0, 0.9 
gluteus_medius = 0, 0.9
gluteus_minimus = 0, 0.9
autochthon = 0, 0.9
iliopsoas = 0, 0.9

# nervous system
brain = 10, 0.9
spinal_cord = 10, 0.9